@startuml
left to right direction
actor "Consumer"


rectangle System{
	Consumer -down->  (Login consumer)
	Consumer -down-> (Display/Add/Delete Booking)
	(Display/Add/Delete Booking) ..> (Login consumer): <<include>>
	Consumer -down-> (Display/Update Consumer)
	(Display/Update Consumer) ..> (Login consumer): <<include>>
	Consumer -down-> (Display/Add Review)
	(Display/Add Review) ..> (Login consumer): <<include>>
}
@enduml