volumes:
    pareidolia_db:

services:
    pareidolia_db:
        image: mysql:8.4.3
        restart: always
        environment:
            MYSQL_DATABASE: "pareidolia"
            MYSQL_ROOT_PASSWORD: "rootroot"
        ports:
            - "3307:3306"
        volumes:
            - pareidolia_db:/var/lib/
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=rootroot --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10