@startuml
actor Consumer
boundary RestUI #DodgerBlue
participant JWTAuthentication #DodgerBlue
participant BookingController #Orange
participant BookingService #Salmon
participant AccountRepository #MediumSeaGreen
participant EventRepository #MediumSeaGreen
participant BookingRepository #MediumSeaGreen
participant BookingConfigurationRepository #MediumSeaGreen
database Database #Salmon

group Consumer booking
Consumer -> RestUI ++ : POST /consumer/booking/get
RestUI -> JWTAuthentication ++ : JWT
JWTAuthentication -> RestUI -- : UserData
RestUI -> BookingController ++ : get(bookingDTO)
BookingController -> BookingService ++ : getBooking
BookingController -> BookingService ++ : getBookings
BookingService -> BookingRepository ++ : findById
BookingRepository -> Database ++ : connection and retrieve data
Database --> BookingRepository -- : Booking
BookingRepository --> BookingService -- : Booking
BookingService -> AccountRepository ++ : findById
AccountRepository -> Database ++ : connection and retrieve data
Database --> AccountRepository -- : IdAccount
'(!Objects.equals(booking.getIdAccount(), consumerService.getData().getId())) '
AccountRepository --> BookingService -- :
Consumer -> RestUI ++ : POST /consumer/booking/create
RestUI -> JWTAuthentication ++ : JWT
JWTAuthentication -> RestUI -- : UserData
RestUI -> BookingController ++ : create(bookingDTO)
BookingController -> BookingService ++ : create
BookingService -> BookingService ++: bookingDTOControls
BookingService -> ConsumerRepository ++ : findById
ConsumerRepository -> Database ++ : connection and retrieve data
Database --> ConsumerRepository -- : ConsumerEntity
ConsumerRepository --> BookingService -- : ConsumerEntity
BookingService -> EventRepository ++ : findById
EventRepository -> Database ++ : connection and retrieve data
Database --> EventRepository -- : EventRepository
EventRepository --> BookingService -- : EventRepository
BookingService -> BookingRepository ++ : countByActiveAndConsumerId
BookingRepository -> Database ++ : connection and retrieve data
Database --> BookingRepository -- : count
BookingRepository --> BookingService -- : count
BookingService -> BookingRepository ++ : findByPeriod
BookingRepository -> Database ++ : connection and retrieve data
Database --> BookingRepository -- : List<BookingEntity>
BookingRepository --> BookingService -- : List<BookingEntity>
BookingService -> BookingConfigurationRepository ++ : findAllByDateOrderByStartTime
BookingConfigurationRepository -> Database ++ : connection and retrieve data
Database --> BookingConfigurationRepository -- : List<BookingConfigurationEntity>
BookingConfigurationRepository --> BookingService -- : List<BookingConfigurationEntity>
BookingService -> BookingConfigurationRepository ++ : findAllByDayOfWeekOrderByStartTime
BookingConfigurationRepository -> Database ++ : connection and retrieve data
Database --> BookingConfigurationRepository -- : List<BookingConfigurationEntity>
BookingConfigurationRepository --> BookingService -- : List<BookingConfigurationEntity>
	loop for each booking day
	BookingService -> BookingService : bookingConfigurationCheck
	end
BookingService -> EventRepository ++ : findById
EventRepository -> Database ++ : connection and retrieve data
Database --> EventRepository -- : TreatmentEntity
EventRepository --> BookingService -- : TreatmentEntity
BookingService -> BookingRepository ++ : save
BookingRepository -> Database ++ : connection and save data
Database --> BookingRepository -- : BookingEntity
BookingRepository --> BookingService -- : BookingEntity
BookingService --> BookingController -- : BookingDTO
BookingController --> RestUI -- : BookingDTO
RestUI --> Consumer -- : 200 OK - JSON Response (BookingDTO)
end
@enduml